# Makefile for PB-GNU KEYNAV, ProBoard PEX Version, for Borland C++
# Copyright (C) 1995 by Branislav L. Slantchev
#
# This file is part of the PB-GNU KEYNAV.
#
# PB-GNU KEYNAV is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2.
#
# PB-GNU KEYNAV is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PB-GNU KEYNAV; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#

.AUTODEPEND
.PATH.obj = .\

CC = bcc
TLINK = tlink
LIBPATH = C:\DEV\LIB
INCLUDEPATH = C:\DEV\INC;C:\DEV\PBLIB\INC

.c.obj:
  $(CC) -c -ml {$< }

EXE_dependencies =     \
	$(LIBPATH)\pb_sdk.obj getopt.obj keynav.obj

keynav.pex: $(EXE_dependencies)
	tlink $(EXE_dependencies), keynav.pex,,, /n /C /x

keynav.obj: keynav.c
getopt.obj: getopt.c
