#
# This file is part of Fortune Cookie v3.00.R1
#
# Copyright (c) 1995, 1997 by Branislav L. Slantchev
# A fine product of Silicon Creations, Inc. (gargoyle)
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the License which accompanies this
# software. This library is distributed in the hope that it will
# be useful, but without any warranty; without even the implied
# warranty of merchantability or fitness for a particular purpose.
#
# You should have received a copy of the License along with this
# library, in the file LICENSE.DOC; if not, write to the address
# below to receive a copy via electronic mail.
#
# You can reach Branislav L. Slantchev (Silicon Creations, Inc.)
# at bslantch@cs.angelo.edu. The file SUPPORT.DOC has the current
# telephone numbers and the postal address for contacts.
#

.autodepend

CC          = bcc +FORTUNE.CFG
TLINK       = tlink
LIBPATH     = E:\SCI\PBL\LIB
INCLUDEPATH = E:\SCI\PBL\H
SDK_OBJ     = E:\C\LIB\PB_SDK.OBJ
PBLIB       = $(LIBPATH)\BCPBL_PX.LIB

.cpp.obj:
	$(CC) -c {$< }

fortune.pex: fortune.cfg fortune.obj
	$(TLINK) /C/n/x $(SDK_OBJ) fortune.obj,fortune.pex,,$(PBLIB)

clean:
	if exist *.obj del *.obj
	if exist *.cfg del *.cfg

fortune.obj: fortune.cfg fortune.cpp

fortune.cfg: makefile
	copy &&|
-ml
-3
-f-
-v
-G
-O
-Og
-Oe
-Om
-Ov
-Ol
-Ob
-Op
-Oi
-Z
-k-
-vi-
-I$(INCLUDEPATH)
-L$(LIBPATH)
-DNDEBUG
-DPB_SDK
-P
| fortune.cfg

