/*
 * This file is part of LZSETUP (Configuration program for Listerz)
 *
 * Copyright (c) 1997 Branislav L. Slantchev (gargoyle)
 * A fine product of Silicon Creations, Inc.
 *
 * This file is released under the terms and conditions of the GNU
 * General Public License Version 2. The full text of the license is
 * supplied in the Copying.Doc file included with this archive. This
 * free software comes with absolutely no warranty, as outlined in the
 * licensing text. You are not allowed to remove this copyright notice.
 *
 * Contact: Branislav L. Slantchev at 73023.262@compuserve.com
*/
#ifndef INCLUDED_LZS_VERS_H
#define INCLUDED_LZS_VERS_H

#define __VERSION__   "v1.01"
#define __VER__       "1.01"
#define __COPYRIGHT__ "lzSetup " __VERSION__ " Copyright (c) 1997 Branislav L. Slantchev"

#endif /* INCLUDED_LZS_VERS_H */
