# Makefile for Borland C++ 3.1
#
# PB-GNU PASSWD ProBoard PEX Version
# Copyright (C) 1995 by Branislav L. Slantchev
#
# This file is part of the PB-GNU PASSWD.
#
# PB-GNU PASSWD is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2.
#
# PB-GNU PASSWD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PB-GNU PASSWD; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#

LIBPATH=C:\DEV\LIB
INCLUDEPATH=C:\DEV\INC


passwd.pex: main.obj date.obj
   tlink $(LIBPATH)\pb_sdk main date, passwd.pex,,, /x/C/n

main.obj: main.c
   bcc -c -ml -I$(INCLUDEPATH) main.c

date.obj: date.c
   bcc -c -ml -I$(INCLUDEPATH) date.c
