
/* ------------------------------------------------------------
 * Filename ............... Version.Hpp
 *
 * General Purpose ........ Version control file
 * ------------------------------------------------------------
 * First date ............. 12-28-94 05:52pm
 *
 * First in version ....... 2.00
 *
 * Written by ............. Alain Schellinck
 *
 * Copyright .............. Nephilim software development
 * ------------------------------------------------------------
 *
 *       See the GNU.DOC file before using this source!
 *
 * ------------------------------------------------------------
 * Revisions:
 * ----------
 *
 *   Date   | By |                  Purpose                   |
 * ---------+----+--------------------------------------------+
 *          |    |                                            |
 *          |    |                                            |
 *          |    |                                            |
 */

/*-------------------------------------------------------------------------*/

#ifndef __VERSION_HPP
#  define __VERSION_HPP

/*-------------------------------------------------------------------------*/

#define  projectCode       "TQ"
#define  projectName       "TheQuote"
#define  projectSpec       "ProBoard One-line Quoter Pex"
#define  versionText       "2.00"
#define  copyrightYear     "1993 - 1995"
#define  author            "Alain Schellinck"
#define  companyName       "Nephilim software development"

#define  xorData           0x45

/*-------------------------------------------------------------------------*/

#endif

/*---------------------------] END OF THE CODE [---------------------------*/
